/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// mol3d-viewer/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Mol3DViewerMobile
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// mol3d-viewer/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  blockWidth: "100%",
  blockHeight: "400px",
  inlineWidth: "150px",
  inlineHeight: "120px",
  inlineAlign: "middle",
  borderWidth: "1px",
  borderColor: "var(--background-modifier-border)",
  backgroundColor: "#000000",
  isTransparent: true,
  styles: { xyz: "stick", pdb: "cartoon", sdf: "sphere", mol2: "stick", cif: "line" }
};
var Mol3DMobileSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5C3A\u5BF8\u4E0E\u5BF9\u9F50\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u5757\u5BBD\u5EA6").addText(
      (t) => t.setValue(this.plugin.settings.blockWidth).onChange(async (v) => {
        this.plugin.settings.blockWidth = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5757\u9AD8\u5EA6").addText(
      (t) => t.setValue(this.plugin.settings.blockHeight).onChange(async (v) => {
        this.plugin.settings.blockHeight = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u8FB9\u6846\u6837\u5F0F\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u8FB9\u6846\u5BBD\u5EA6").addText(
      (t) => t.setValue(this.plugin.settings.borderWidth).onChange(async (v) => {
        this.plugin.settings.borderWidth = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8FB9\u6846\u989C\u8272").addColorPicker(
      (cp) => cp.setValue(this.plugin.settings.borderColor.startsWith("var") ? "#cccccc" : this.plugin.settings.borderColor).onChange(async (v) => {
        this.plugin.settings.borderColor = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u5206\u5B50\u80CC\u666F\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u900F\u660E\u80CC\u666F").setDesc("\u5F00\u542F\u540E\u5C06\u5FFD\u7565\u80CC\u666F\u989C\u8272\u8BBE\u7F6E").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.isTransparent).onChange(async (v) => {
        this.plugin.settings.isTransparent = v;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (!this.plugin.settings.isTransparent) {
      new import_obsidian.Setting(containerEl).setName("\u80CC\u666F\u989C\u8272").addColorPicker(
        (cp) => cp.setValue(this.plugin.settings.backgroundColor).onChange(async (v) => {
          this.plugin.settings.backgroundColor = v;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h2", { text: "\u683C\u5F0F\u9ED8\u8BA4\u98CE\u683C" });
    const styleOptions = { "stick": "Stick", "sphere": "Sphere", "line": "Line", "cartoon": "Cartoon (\u5149\u8C31\u8272)" };
    Object.keys(this.plugin.settings.styles).forEach((fmt) => {
      new import_obsidian.Setting(containerEl).setName(fmt.toUpperCase()).addDropdown(
        (drop) => drop.addOptions(styleOptions).setValue(this.plugin.settings.styles[fmt]).onChange(async (v) => {
          this.plugin.settings.styles[fmt] = v;
          await this.plugin.saveSettings();
        })
      );
    });
  }
};

// mol3d-viewer/view.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_MOL3D = "mol3d-view";
var Mol3DView = class extends import_obsidian2.TextFileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MOL3D;
  }
  getDisplayText() {
    return this.file ? this.file.name : "Mol3D Viewer";
  }
  getIcon() {
    return "box";
  }
  async onOpen() {
    this.contentEl.empty();
    this.viewContainer = this.contentEl.createDiv({ cls: "mol3d-view-container" });
    this.moleculeEl = this.viewContainer.createDiv({ cls: "mol3d-molecule-container" });
    this.textPreviewEl = this.viewContainer.createDiv({ cls: "mol3d-text-preview" });
  }
  setViewData(data, clear) {
    this.data = data;
    if (this.file) {
      this.plugin.renderMolecule(this.moleculeEl, this.file.extension, data, "view");
    }
    this.textPreviewEl.setText(data);
  }
  getViewData() {
    return this.data;
  }
  clear() {
    this.moleculeEl.empty();
    this.textPreviewEl.empty();
  }
};

// mol3d-viewer/main.ts
var Mol3DViewerMobile = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new Mol3DMobileSettingTab(this.app, this));
    try {
      await this.injectDependency("3Dmol-min.js", "$3Dmol");
      try {
        this.registerView(
          VIEW_TYPE_MOL3D,
          (leaf) => new Mol3DView(leaf, this)
        );
      } catch (e) {
        console.log(`[Mol3D] View type ${VIEW_TYPE_MOL3D} already registered.`);
      }
      const formats = Object.keys(this.settings.styles);
      formats.forEach((ext) => {
        try {
          this.registerExtensions([ext], VIEW_TYPE_MOL3D);
        } catch (e) {
          console.log(`[Mol3D] \u6269\u5C55\u540D .${ext} \u5DF2\u88AB\u63A5\u7BA1`);
        }
      });
      this.initProcessors();
      this.applySettings();
      console.log("Mol3D Viewer: \u5DF2\u5F00\u542F\u6587\u4EF6\u5173\u8054\u4E0E\u589E\u5F3A\u5D4C\u5165\u6E32\u67D3");
    } catch (e) {
      console.error("Mol3D Viewer \u52A0\u8F7D\u5931\u8D25", e);
    }
  }
  async injectDependency(fileName, globalVar) {
    return new Promise((resolve) => {
      if (window[globalVar])
        return resolve(window[globalVar]);
      const loadCDN = () => {
        console.log(`[Mol3D] \u5C1D\u8BD5\u4ECE CDN \u56DE\u9000\u52A0\u8F7D 3Dmol-min.js ...`);
        const script = document.createElement("script");
        script.src = "https://cdnjs.cloudflare.com/ajax/libs/3Dmol/2.4.0/3Dmol-min.js";
        script.type = "text/javascript";
        script.onload = () => resolve(window[globalVar]);
        script.onerror = () => resolve(null);
        document.head.appendChild(script);
      };
      try {
        const adapter = this.app.vault.adapter;
        const resourcePath = adapter.getResourcePath((0, import_obsidian3.normalizePath)(this.manifest.dir + "/" + fileName));
        const script = document.createElement("script");
        script.src = resourcePath;
        script.type = "text/javascript";
        script.onload = () => resolve(window[globalVar]);
        script.onerror = loadCDN;
        document.head.appendChild(script);
      } catch (e) {
        loadCDN();
      }
    });
  }
  // 解析关键词功能：支持 Key:Value, Key=Value 以及中英文
  parseKeywords(content) {
    const parts = content.split(/^---$/m);
    let keywords = {};
    let finalContent = content;
    if (parts.length >= 2) {
      const keywordSection = parts[0].trim();
      finalContent = parts.slice(1).join("---").trim();
      const rawKeys = keywordSection.split(/[,，\n]/);
      rawKeys.forEach((raw) => {
        const pair = raw.trim().split(/[:：=]/);
        if (pair.length === 2) {
          keywords[pair[0].trim().toLowerCase()] = pair[1].trim();
        } else if (pair[0].trim()) {
          keywords[pair[0].trim().toLowerCase()] = true;
        }
      });
    }
    return { keywords, finalContent };
  }
  // 核心渲染函数
  async renderMolecule(parentContainer, format, rawContent, isEmbed = false) {
    if (parentContainer.clientWidth === 0) {
      setTimeout(() => this.renderMolecule(parentContainer, format, rawContent, isEmbed), 200);
      return;
    }
    parentContainer.empty();
    if (!window.$3Dmol) {
      parentContainer.setText("3Dmol.js \u5E93\u672A\u52A0\u8F7D\uFF0C\u8BF7\u786E\u4FDD\u63D2\u4EF6\u76EE\u5F55\u4E0B\u786E\u5B9E\u5B58\u5728 3Dmol-min.js \u6587\u4EF6");
      return;
    }
    const { keywords, finalContent } = this.parseKeywords(rawContent);
    const wrapper = parentContainer.createDiv({ cls: "mol3d-wrapper" });
    const isMobileScreen = window.innerWidth <= 600;
    let finalWidth = keywords.width || this.settings.blockWidth;
    let finalHeight = keywords.height || this.settings.blockHeight;
    if (isMobileScreen && isEmbed !== "view") {
      finalWidth = "100%";
    }
    let finalBorderColor = keywords.bc || keywords["border-color"] || keywords.\u8FB9\u6846\u989C\u8272 || this.settings.borderColor;
    let finalBorderWidth = keywords.bw || keywords["border-width"] || keywords.\u8FB9\u6846\u5BBD\u5EA6 || this.settings.borderWidth;
    if (isEmbed === "view") {
      wrapper.style.border = "none";
      wrapper.style.borderRadius = "0";
      wrapper.style.height = "100%";
      wrapper.style.width = "100%";
    } else {
      wrapper.style.border = `${finalBorderWidth} solid ${finalBorderColor}`;
      wrapper.style.borderRadius = "8px";
      wrapper.style.height = finalHeight;
      wrapper.style.width = finalWidth;
      const isFullWidth = finalWidth.toString().trim() === "100%";
      wrapper.style.margin = isFullWidth ? "0" : "1em auto";
    }
    let renderBg = this.settings.backgroundColor;
    let renderTransparent = this.settings.isTransparent;
    if (keywords.bg || keywords.\u80CC\u666F) {
      renderBg = keywords.bg || keywords.\u80CC\u666F;
      renderTransparent = renderBg === "transparent" || renderBg === "none";
    }
    wrapper.style.backgroundColor = renderTransparent ? "transparent" : renderBg;
    const titleText = keywords.title || keywords.\u6807\u9898;
    if (titleText) {
      const titleBar = wrapper.createDiv({ cls: "mol3d-title-bar" });
      titleBar.setText(titleText);
    }
    const canvasArea = wrapper.createDiv({ cls: "mol3d-canvas-area" });
    const viewer = window.$3Dmol.createViewer(canvasArea, {
      backgroundColor: renderTransparent ? "none" : renderBg
    });
    let userStyle = keywords.style || keywords.\u98CE\u683C || this.settings.styles[format.toLowerCase()] || "stick";
    let styleObj = {};
    if (userStyle === "cartoon") {
      styleObj = { cartoon: { color: "spectrum" } };
    } else {
      styleObj[userStyle] = {};
    }
    try {
      viewer.addModel(finalContent, format.toLowerCase());
      viewer.setStyle({}, styleObj);
      viewer.zoomTo();
      const bgColorHex = renderBg.startsWith("#") ? renderBg.replace("#", "0x") : renderBg;
      const opacity = renderTransparent ? 0 : 1;
      try {
        const colorVal = parseInt(bgColorHex.startsWith("0x") ? bgColorHex : bgColorHex.startsWith("#") ? bgColorHex.replace("#", "0x") : "0x000000");
        viewer.setBackgroundColor(isNaN(colorVal) ? 0 : colorVal, opacity);
      } catch (e) {
        viewer.setBackgroundColor(0, opacity);
      }
      viewer.render();
    } catch (err) {
      canvasArea.setText("\u6A21\u578B\u89E3\u6790\u5931\u8D25");
    }
    const ro = new ResizeObserver(() => {
      if (wrapper.clientWidth > 0) {
        viewer.resize();
        viewer.render();
      }
    });
    ro.observe(wrapper);
    return viewer;
  }
  initProcessors() {
    const formats = Object.keys(this.settings.styles);
    const plugin = this;
    formats.forEach((fmt) => {
      try {
        this.registerMarkdownCodeBlockProcessor(fmt, (source, el, ctx) => {
          const div = el.createDiv({ cls: "mol3d-viewer-container-block" });
          const child = new class extends import_obsidian3.MarkdownRenderChild {
            async onload() {
              const updateRender = async () => {
                let modelData = source.trim(), finalFmt = fmt;
                if (modelData.includes("[[") && modelData.includes("]]") && !modelData.includes("---")) {
                  const match = modelData.match(/\[\[(.*?)\]\]/);
                  if (match) {
                    const file = plugin.app.metadataCache.getFirstLinkpathDest(match[1], ctx.sourcePath || "");
                    if (file instanceof import_obsidian3.TFile) {
                      modelData = await plugin.app.vault.read(file);
                      finalFmt = file.extension;
                    }
                  }
                }
                await plugin.renderMolecule(div, finalFmt, modelData, true);
              };
              await updateRender();
              this.registerEvent(plugin.app.workspace.on("mol3d:update", () => updateRender()));
            }
          }(div);
          ctx.addChild(child);
        });
      } catch (e) {
        console.log(`[Mol3D] Code block processor for ${fmt} is already registered by another plugin.`);
      }
    });
    this.registerMarkdownPostProcessor((el, ctx) => {
      const embeds = el.querySelectorAll(".internal-embed");
      embeds.forEach((node) => {
        var _a;
        const src = node.getAttribute("src");
        if (!src)
          return;
        const extension = (_a = src.split(".").pop()) == null ? void 0 : _a.toLowerCase();
        if (extension && formats.includes(extension)) {
          node.classList.add("mol3d-embed-active");
          const child = new class extends import_obsidian3.MarkdownRenderChild {
            async onload() {
              const updateRender = async (retryCount = 0) => {
                const file = plugin.app.metadataCache.getFirstLinkpathDest(src, ctx.sourcePath || "");
                if (file) {
                  const data = await plugin.app.vault.read(file);
                  await plugin.renderMolecule(node, extension, data, true);
                } else if (retryCount < 10) {
                  setTimeout(() => updateRender(retryCount + 1), 300);
                }
              };
              await updateRender();
              this.registerEvent(plugin.app.workspace.on("mol3d:update", () => updateRender()));
            }
          }(node);
          ctx.addChild(child);
        }
      });
      const textNodes = el.querySelectorAll("p, li, code");
      textNodes.forEach((node) => {
        if (node.classList.contains("internal-embed") || node.closest(".internal-embed"))
          return;
        const text = node.innerText;
        const regex = new RegExp(`(${formats.join("|")})\\((.*?)\\)`, "gi");
        if (regex.test(text)) {
          const frag = document.createDocumentFragment();
          let lastIndex = 0;
          regex.lastIndex = 0;
          let match;
          while ((match = regex.exec(text)) !== null) {
            const currentMatch = match;
            frag.appendChild(document.createTextNode(text.slice(lastIndex, currentMatch.index)));
            const span = document.createElement("span");
            span.classList.add("mol3d-inline-container");
            const child = new class extends import_obsidian3.MarkdownRenderChild {
              async onload() {
                const updateRender = async () => {
                  let modelData = currentMatch[2].trim(), finalFmt = currentMatch[1];
                  if (modelData.startsWith("[[") && modelData.endsWith("]]")) {
                    const file = plugin.app.metadataCache.getFirstLinkpathDest(modelData.substring(2, modelData.length - 2), ctx.sourcePath || "");
                    if (file) {
                      modelData = await plugin.app.vault.read(file);
                      finalFmt = file.extension;
                    }
                  }
                  await plugin.renderMolecule(span, finalFmt, modelData, false);
                };
                await updateRender();
                this.registerEvent(plugin.app.workspace.on("mol3d:update", () => updateRender()));
              }
            }(span);
            ctx.addChild(child);
            frag.appendChild(span);
            lastIndex = regex.lastIndex;
          }
          frag.appendChild(document.createTextNode(text.slice(lastIndex)));
          node.replaceWith(frag);
        }
      });
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applySettings();
    this.app.workspace.trigger("mol3d:update");
  }
  applySettings() {
    const root = document.documentElement;
    root.style.setProperty("--mol3d-block-width", this.settings.blockWidth);
    root.style.setProperty("--mol3d-block-height", this.settings.blockHeight);
  }
};
